name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'           # <-- caches node_modules between runs

      - name: Install dependencies
        run: npm ci              # <-- use ci to match package-lock.json exactly

      - name: Rebuild native modules (optional but fixes lightningcss issues)
        run: npm rebuild lightningcss

      - name: Build and Export Next.js
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
